var a = {
	"userId": 447,
	"loginName": "17708109894",
	"nickName": "陈俊采购商",
	"mobile": "17708109894",
	"sysId": "8",
	"typeId": "buyer",
	"typeCode": "202",
	"token": "bd1a72cd-c3a2-4acf-a886-27948707029d"
}
var c = [{
		"productId": 53,
		"productName": "123",
		"skuId": 77,
		"skuName": "商品图片呢",
		"skuMeasure": "002",
		"skuMeasureName": "斤",
		"quantity": 1,
		"chargingModel": "1",
		"oriPrice": 100,
		"price": 100
	},
	{
		"productId": 11,
		"productName": "大米",
		"skuId": 20,
		"skuName": "大米（5斤装/计件）",
		"skuMeasure": "005",
		"skuMeasureName": "袋",
		"quantity": 1,
		"chargingModel": "2",
		"oriPrice": 360,
		"price": 1700
	}
]
var b = {
	"settlementGoods": [{
		"id": 53,
		"buyerId": 202,
		"productId": 39,
		"productName": "大白菜",
		"skuId": 61,
		"skuName": "按斤算",
		"quantity": 1,
		"comment": "",
		"sellerId": 38,
		"skuMeasure": "002",
		"skuMeasureName": "斤",
		"chargingModel": "1",
		"promotionBasePrice": "1.0",
		"promotionPrice": "1.0",
		"basePrice": "1.0",
		"price": "1.0",
		"skuPicUrl": "",
		"isCollection": "0",
		"proPicUrl": "upload/20180622/productOnline/MTUyOTY1OTMzNTEzMw==",
		"btnText": "备注",
		"showRemarks": false
	}, {
		"id": 52,
		"buyerId": 202,
		"productId": 27,
		"productName": "花蛤",
		"skuId": 38,
		"skuName": "按斤算",
		"quantity": 1,
		"comment": "",
		"sellerId": 38,
		"skuMeasure": "002",
		"skuMeasureName": "斤",
		"chargingModel": "1",
		"promotionBasePrice": "5.4",
		"promotionPrice": "5.4",
		"basePrice": "5.4",
		"price": "5.4",
		"skuPicUrl": "upload/20180622/productsku/MTUyOTY1ODc3MTAzMA==",
		"isCollection": "120",
		"proPicUrl": "upload/20180622/productOnline/MTUyOTY1ODcyMjI0Mg==",
		"btnText": "备注",
		"showRemarks": false
	}, {
		"id": 51,
		"buyerId": 202,
		"productId": 18,
		"productName": "草鱼",
		"skuId": 28,
		"skuName": "按斤算",
		"quantity": 1,
		"comment": "",
		"sellerId": 38,
		"skuMeasure": "006",
		"skuMeasureName": "条",
		"chargingModel": "1",
		"promotionBasePrice": "9.8",
		"promotionPrice": "9.8",
		"basePrice": "9.8",
		"price": "9.8",
		"skuPicUrl": "",
		"isCollection": "0",
		"proPicUrl": "upload/20180622/productOnline/MTUyOTY1ODU2ODkwMQ==",
		"btnText": "备注",
		"showRemarks": false
	}]
}